{{- if .Values.global.ingress.enabled -}}
{{- $fullName := include "flink.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "flink.labels" . | indent 4 }}
  {{- with .Values.global.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
{{- if .Values.global.ingress.tls }}
  tls:
  {{- range .Values.global.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.global.ingress.host }}
      http:
        paths:
          - path: {{ .Values.global.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-jobmanager
                port: 
                  number: 8081
{{- end }}
