{{- if .Values.global.jobmanager.statefulset }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flink.fullname" . }}-jobmanager-headless
  labels:
{{ include "flink.labels" . | indent 4 }}
    component: jobmanager
{{- if .Values.global.jobmanager.service.headless.annotations }}
  annotations:
{{ toYaml .Values.global.jobmanager.service.headless.annotations | indent 4 }}
{{- end }}
spec:
  clusterIP: None
  ports:
    {{- range $name, $port := .Values.global.jobmanager.ports }}
    - port: {{ $port }}
      targetPort: {{ $name }}
      protocol: TCP
      name: {{ $name }}
    {{- end }}
    {{- if .Values.global.flink.monitoring.enabled }}
    - port: {{ .Values.global.flink.monitoring.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "flink.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: jobmanager
{{- end }}
