{{- if and .Values.global.secrets.bitnamiSealedSecrets.enabled .Values.global.secrets.bitnamiSealedSecrets.sealedSecretFiles }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  {{- if .Values.global.secrets.bitnamiSealedSecrets.sealedSecretFilesAnnotations }}
  annotations:
    {{- range $key, $val := .Values.global.secrets.bitnamiSealedSecrets.sealedSecretFilesAnnotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}
  name: {{ .Release.Name }}-secretfiles
spec:
  encryptedData:
    {{- range $key, $val := .Values.global.secrets.bitnamiSealedSecrets.sealedSecretFiles }}
    {{ $key }}: {{ $val }}
    {{- end }}
{{- end }}