apiVersion: apps/v1
{{- if .Values.global.taskmanager.statefulset }}
kind: StatefulSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: {{ include "flink.fullname" . }}-taskmanager
  labels:
{{ include "flink.labels" . | indent 4 }}
    component: taskmanager
  annotations:
  {{- range $key, $value := .Values.global.taskmanager.annotations }}
    {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
spec:
  replicas: {{ .Values.global.taskmanager.replicaCount }}
  {{- if .Values.global.taskmanager.statefulset }}
  podManagementPolicy: {{ .Values.global.taskmanager.podManagementPolicy }}
  {{- else }}
  strategy:
    type: Recreate
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flink.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: taskmanager
  {{- if .Values.global.taskmanager.statefulset }}
  serviceName: {{ include "flink.fullname" . }}-taskmanager
  {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "flink.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: taskmanager
      annotations:
      {{- range $key, $value := .Values.global.taskmanager.podAnnotations }}
        {{ $key | quote }}: {{ $value | quote }}
      {{- end }}
    spec:
    {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "taskmanager.serviceAccount" . }}
      securityContext:
        {{ toYaml .Values.global.securityContext | indent 8 }}
      initContainers:
      {{- range $ct, $params := .Values.global.taskmanager.initContainers }}
        - name: {{ $ct }}
          image: {{ $params.image }}
          command:
          {{- range $params.command }}
            - {{ . }}
          {{- end }}
      {{- end }}
      containers:
        - name: taskmanager
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          workingDir: {{ .Values.global.flink.workDir }}
          command:
            - "/bin/bash"
            - "-c"
            - {{ include "taskmanager.command" . | quote }}
          env:
            - name: JVM_ARGS
              value: {{ tpl .Values.global.taskmanager.jvmArgs . | quote }}
          {{- if .Values.global.extraEnvs }}
          {{- toYaml .Values.global.extraEnvs | nindent 12 }}
          {{- end }}
          {{- if .Values.global.jobmanager.extraEnvs }}
          {{- toYaml .Values.global.taskmanager.extraEnvs | nindent 12 }}
          {{- end }}
          envFrom:
          {{- if and .Values.global.secrets.bitnamiSealedSecrets.enabled .Values.global.secrets.bitnamiSealedSecrets.sealedSecretEnvs }}
            - secretRef:
                name: {{ .Release.Name }}-secretenvs
          {{- end }}
          ports:
          {{- range $name, $port := .Values.global.taskmanager.ports }}
            - containerPort: {{ $port }}
              name: {{ $name }}
          {{- end }}
          {{- if .Values.global.flink.monitoring.enabled }}
            - containerPort: {{ .Values.global.flink.monitoring.port }}
              name: metrics
          {{- end }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.global.taskmanager.ports.rpc }}
            initialDelaySeconds: {{ .Values.global.taskmanager.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.taskmanager.livenessProbe.periodSeconds }}
          volumeMounts:
            - name: flink-config-volume
              mountPath: {{ .Values.global.flink.workDir }}/conf
          {{- if and .Values.global.taskmanager.persistent.enabled .Values.global.taskmanager.statefulset }}
            - name: taskmanager-data
              mountPath: {{ .Values.global.taskmanager.persistent.mountPath }}
          {{- end }}
          {{- range $secret := .Values.global.secrets.kubernetesSecrets }}
            {{- if $secret.mountPath }}
              {{- if $secret.keys }}
                {{- range $key := $secret.keys }}
            - name: {{ include "flink.fullname" $ }}-{{ $secret.name }}
              mountPath: {{ $secret.mountPath }}/{{ $key }}
              subPath: {{ $key }}
              readOnly: true
                {{- end }}
              {{- else }}
            - name: {{ include "flink.fullname" $ }}-{{ $secret.name }}
              mountPath: {{ $secret.mountPath }}
              readOnly: true
              {{- end }}
            {{- end }}
          {{- end }}
          {{- if .Values.global.taskmanager.extraVolumeMounts -}}
            {{ toYaml .Values.global.taskmanager.extraVolumeMounts | nindent 12 }}
          {{- end }}
          {{- if and (and .Values.global.secrets.bitnamiSealedSecrets.enabled .Values.global.secrets.bitnamiSealedSecrets.sealedSecretFiles) .Values.global.secrets.bitnamiSealedSecrets.sealedSecretFilesPath }}
            - name: sealed-secret-files
              mountPath: {{ .Values.global.secrets.bitnamiSealedSecrets.sealedSecretFilesPath }}
          {{- end }}
          resources:
            {{- toYaml .Values.global.taskmanager.resources | nindent 12 }}

      volumes:
        - name: flink-config-volume
          configMap:
            name: {{ include "flink.fullname" . }}-config
            items:
              - key: flink-conf-taskmanager.yaml
                path: flink-conf.yaml
              - key: log4j.properties
                path: log4j.properties
              - key: log4j.properties
                path: log4j-console.properties
              - key: security.properties
                path: security.properties
              {{- if .Values.global.jobmanager.highAvailability.enabled }}
              - key: masters
                path: masters
              {{- end }}
      {{- range .Values.global.secrets.kubernetesSecrets }}
        - name: {{ include "flink.fullname" $ }}-{{ .name }}
          secret:
            secretName: {{ .name }}
      {{- end }}
      {{- if .Values.global.taskmanager.extraVolumes -}}
        {{ toYaml .Values.global.taskmanager.extraVolumes | nindent 8 }}
      {{- end }}
      {{- if and (and .Values.global.secrets.bitnamiSealedSecrets.enabled .Values.global.secrets.bitnamiSealedSecrets.sealedSecretFiles) .Values.global.secrets.bitnamiSealedSecrets.sealedSecretFilesPath }}
        - name: sealed-secret-files
          secret:
            secretName: {{ .Release.Name }}-secretfiles
      {{- end }}

      {{- with .Values.global.taskmanager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.global.taskmanager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.global.taskmanager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- if and .Values.global.taskmanager.persistent.enabled .Values.global.taskmanager.statefulset }}
  volumeClaimTemplates:
    - metadata:
        name: taskmanager-data
        labels:
{{ include "flink.labels" . | indent 10 }}
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if eq (kindIs "invalid" .Values.global.taskmanager.persistent.storageClass) false }}
        storageClassName: {{ .Values.global.taskmanager.persistent.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.global.taskmanager.persistent.size }}
{{- end }}
